### ISSUE TITLE
Double click does not work on Firefox

### ISSUE THREAD

**Issue by kmcsekar** [SeleniumHQ/selenium-google-code-issue-archive#8764]
With selenium 2.53, I couldn't get the double click work on SVG element.
I'm trying to perform double click on an SVG element.
It use to work on selenium 2.48.  But it does not work on selenium 2.53.
This is on Firefox browser.

If you decide to close the issue, please state a reason before closing the issue.
Is this a known issue? or please let me know if I'm missing something here.

**Comment by lukeis** [comment]
read the text when attempting to create a new issue on this repo...

https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/new
